  /// \file AHCALRawModule.h
/*
 *
 *-------------------------------------------------------------
 * AHCALRawModule.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef AHCALRAWMODULE_H
#define AHCALRAWMODULE_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** AHCALRawModule class
 */ 
class AHCALRawModule : public DQMAnalysisModule
{
public:
	AHCALRawModule();
	~AHCALRawModule();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:
	DQMMonitorElementPtr                        m_pNHitElement;
	DQMMonitorElementPtr                        m_pADC_hitbit0;
	DQMMonitorElementPtr                        m_pADC_hitbit1;
	DQMMonitorElementPtr                        m_pTDC_hitbit0;
	DQMMonitorElementPtr                        m_pTDC_hitbit1;

	DQMMonitorElementPtr                        m_pADC_hitbit0_ch1;
	DQMMonitorElementPtr                        m_pADC_hitbit1_ch1;
	DQMMonitorElementPtr                        m_pTDC_hitbit0_ch1;
	DQMMonitorElementPtr                        m_pTDC_hitbit1_ch1;

	//std::vector<DQMMonitorElementPtr> m_pADC_hitbit0_ch(36);
	//std::vector<DQMMonitorElementPtr> m_pADC_hitbit1_ch(36);
	//std::vector<DQMMonitorElementPtr> m_pTDC_hitbit0_ch(36);
	//std::vector<DQMMonitorElementPtr> m_pTDC_hitbit1_ch(36);

	/* DQMMonitorElement                        *m_pHitsEnergyElement; */
	/* DQMMonitorElement                        *m_pXZProfileElement; */
	/* DQMMonitorElement                        *m_pYZProfileElement; */
	/* DQMMonitorElement                        *m_pXYProfileElement; */
	/* DQMMonitorElement                        *m_pLayerProfileElement; */
	/* DQMMonitorElement                        *m_pTimeElement; */
	/* DQMMonitorElement                        *m_pLastXZProfileElement; */
	/* DQMMonitorElement                        *m_pLastYZProfileElement; */
	/* DQMMonitorElement                        *m_pLastXYProfileElement; */

	bool                                      m_dumpEvent;
}; 

} 

#endif  //  AHCALRAWMODULE_H
