  /// \file DQMMarlinModule.h
/*
 *
 * DQMMarlinModule.h header template automatically generated by a class generator
 * Creation date : lun. mars 7 2016
 *
 * This file is part of DQM4ILC libraries.
 * 
 * DQM4ILC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4ILC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4ILC.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DQMMARLINMODULE_H
#define DQMMARLINMODULE_H

// -- dqm4hep headers
#include "dqm4hep/DQMAnalysisModule.h"
#include "dqm4hep/DQMXmlHelper.h"

// -- lcio headers
#include "EVENT/LCEvent.h"

namespace marlin { class IParser; }

// external tiny xml impl
class TiXmlElement;

namespace dqm4ilc
{

class DQMMarlin;

/** 
 * @brief DQMMarlinModule class.
 *
 *        Marlin-DQM4HEP binding. Allows to run Marlin in the DQM4HEP framework.
 *        User must inherit this interface and implement the virtual methods.
 *        This module runs a Marlin application before to callback user methods.
 *        For example, the userProcessEvent(evt) is called after processing an event
 *        in the Marlin framework.
 */ 
class DQMMarlinModule : public dqm4hep::DQMAnalysisModule
{
public:
	/** Constructor
	 */
	DQMMarlinModule();

	/** Destructor
	 */
	virtual ~DQMMarlinModule();

protected:
	/** Read settings from a tiny xml handle
	 */
	virtual dqm4hep::StatusCode userReadSettings(const dqm4hep::TiXmlHandle xmlHandle) = 0;

	/** Initialize the marlin module
	 */
	virtual dqm4hep::StatusCode userInitModule() = 0;

	/** Called when a new run is started
	 */
	virtual dqm4hep::StatusCode userStartOfRun(dqm4hep::DQMRun *pRun) = 0;

	/** Called when a new cycle is started
	 */
	virtual dqm4hep::StatusCode userStartOfCycle() = 0;

	/** Process a LCEvent in the DQM4HEP framework
	 */
	virtual dqm4hep::StatusCode userProcessEvent(EVENT::LCEvent *pLCEvent) = 0;

	/** Called when a cycle ends
	 */
	virtual dqm4hep::StatusCode userEndOfCycle() = 0;

	/** Called when a run ends
	 */
	virtual dqm4hep::StatusCode userEndOfRun(dqm4hep::DQMRun *pRun) = 0;

	/** Call at module application termination
	 */
	virtual dqm4hep::StatusCode userEndModule() = 0;

private:
	// from DQMAnalysisModule
	dqm4hep::StatusCode readSettings(const dqm4hep::TiXmlHandle xmlHandle);
	dqm4hep::StatusCode initModule();
	dqm4hep::StatusCode startOfRun(dqm4hep::DQMRun *pRun);
	dqm4hep::StatusCode startOfCycle();
	dqm4hep::StatusCode processEvent(dqm4hep::DQMEvent *pEvent);
	dqm4hep::StatusCode endOfCycle();
	dqm4hep::StatusCode endOfRun(dqm4hep::DQMRun *pRun);
	dqm4hep::StatusCode endModule();

private:
	DQMMarlin                  *m_pMarlin;
	std::string                 m_marlinSteeringFile;
};

} 

#endif  //  DQMMARLINMODULE_H
